### ISSUE TITLE
Problem launching sample.

### ISSUE THREAD

**Issue by lionhive** [saitoxu/SendBirdSample#1]
I try to launch but it hangs on npm start with latest tools. 

$ npm install

> fsevents@1.1.3 install /Users/admin/Documents/src/evaluations/NativeBird/node_modules/fsevents
> node install

[fsevents] Success: "/Users/admin/Documents/src/evaluations/NativeBird/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote

> websocket@1.0.24 install /Users/admin/Documents/src/evaluations/NativeBird/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
added 956 packages in 65.366s
Tomass-MacBook-Pro:NativeBird admin$ yarn start
yarn run v1.3.2
$ react-native start
Scanning folders for symlinks in /Users/admin/Documents/src/evaluations/NativeBird/node_modules (15ms)
 ┌────────────────────────────────────────────────────────────────────────────┐ 
 │  Running Metro Bundler on port 8081.                                       │ 
 │                                                                            │ 
 │  Keep Metro Bundler running while developing on any JS projects. Feel      │ 
 │  free to close this tab and run your own Metro Bundler  instance if you    │ 
 │  prefer.                                                                   │ 
 │                                                                            │ 
 │  https://github.com/facebook/react-native                                  │ 
 │                                                                            │ 
 └────────────────────────────────────────────────────────────────────────────┘ 
Looking for JS files in
   /Users/admin/Documents/src/evaluations/NativeBird 

Metro Bundler ready.

Loading dependency graph, done.
 
**(hangs here)**

**Comment by saitoxu** [comment]
Have you tried building with Xcode?

**Comment by saitoxu** [comment]
I think you may use a wrong repository.

> /Users/admin/Documents/src/evaluations/NativeBird

I close this issue, if there is a problem, please reopen this.
